/** Seed fixtures for the Settings dev preview (see mockSettingsClient.ts). */
const NOW = new Date("2026-07-15T20:00:00.000Z");
const iso = (offsetDays = 0) =>
  new Date(NOW.getTime() + offsetDays * 86_400_000).toISOString();

export const PROFILE_ID = "demo-profile-settings";
export const ARTIST_ID = "demo-artist-settings";

export const seedTables = {
  profiles: [
    {
      id: PROFILE_ID,
      display_name: "Jayden Cole",
      handle: "jayden.ink",
      bio: "Baltimore-based, blackwork & fine line.",
      avatar_url: null,
      email: "demo-booking-artist@inkd.test",
      city: "Baltimore",
      state: "MD",
      phone: null,
      is_artist: true,
      is_public: true,
      created_at: iso(-120),
      updated_at: iso(-1),
    },
  ],
  artist_profiles: [
    {
      id: ARTIST_ID,
      profile_id: PROFILE_ID,
      bio: "Baltimore-based, blackwork & fine line. Booking custom pieces and touch-ups.",
      tagline: "Blackwork & fine line",
      styles: ["blackwork", "fine_line"],
      classification: "private_suite",
      travel_fly_out: false,
      travel_house_calls: true,
      travel_at_home: false,
      accepts_new_clients: true,
      years_experience: 7,
      instagram_handle: "jayden.ink",
      onboarding_step: 5,
      onboarding_completed_at: iso(-90),
      is_published: true,
      stripe_account_id: null,
      stripe_charges_enabled: false,
      stripe_details_submitted: false,
      stripe_identity_verified: false,
      stripe_onboarding_completed_at: null,
      stripe_payouts_enabled: false,
      plan: "free",
      created_at: iso(-120),
      updated_at: iso(-1),
    },
  ],
  styles: [
    { id: "style-1", slug: "blackwork", name: "Blackwork", category: "technique", description: null, sort_order: 1 },
    { id: "style-2", slug: "fine_line", name: "Fine line", category: "technique", description: null, sort_order: 2 },
    { id: "style-3", slug: "realism", name: "Realism", category: "technique", description: null, sort_order: 3 },
    { id: "style-4", slug: "traditional", name: "Traditional", category: "technique", description: null, sort_order: 4 },
  ],
  portfolio_pieces: [
    {
      id: "piece-1",
      artist_id: ARTIST_ID,
      image_url: "https://picsum.photos/seed/inkd-piece-1/600/600",
      title: "Forearm blackwork",
      description: null,
      placement: "forearm",
      style_tags: ["blackwork"],
      is_public: true,
      is_healed: true,
      sort_order: 0,
      post_id: null,
      instagram_media_id: null,
      created_at: iso(-40),
      updated_at: iso(-40),
    },
    {
      id: "piece-2",
      artist_id: ARTIST_ID,
      image_url: "https://picsum.photos/seed/inkd-piece-2/600/600",
      title: "Fine line florals",
      description: null,
      placement: "shoulder",
      style_tags: ["fine_line"],
      is_public: true,
      is_healed: true,
      sort_order: 1,
      post_id: null,
      instagram_media_id: null,
      created_at: iso(-30),
      updated_at: iso(-30),
    },
  ],
  // --- Dashboard stats fixtures ------------------------------------------
  booking_requests: [
    {
      id: "req-1",
      artist_id: ARTIST_ID,
      client_id: "client-1",
      status: "pending",
      service_id: null,
      location_id: null,
      placement: "forearm",
      size_description: "4in",
      description: "Custom blackwork piece",
      reference_uploads: [],
      preferred_dates: [],
      budget_min_cents: 20000,
      budget_max_cents: 40000,
      has_medical_flags: false,
      is_cover_up: false,
      is_first_tattoo: false,
      created_at: iso(-2),
      updated_at: iso(-2),
    },
    {
      id: "req-2",
      artist_id: ARTIST_ID,
      client_id: "client-2",
      status: "pending",
      service_id: null,
      location_id: null,
      placement: "shoulder",
      size_description: "6in",
      description: "Fine line florals",
      reference_uploads: [],
      preferred_dates: [],
      budget_min_cents: 30000,
      budget_max_cents: 50000,
      has_medical_flags: false,
      is_cover_up: false,
      is_first_tattoo: false,
      created_at: iso(-1),
      updated_at: iso(-1),
    },
  ],
  bookings: [
    { id: "bk-1", artist_id: ARTIST_ID, client_id: "client-3", request_id: null, service_id: null, status: "confirmed", title: "Session 1", total_price_cents: 40000, deposit_cents: 10000, notes: null, created_at: iso(-60), updated_at: iso(-60) },
    { id: "bk-2", artist_id: ARTIST_ID, client_id: "client-3", request_id: null, service_id: null, status: "completed", title: "Touch-up", total_price_cents: 15000, deposit_cents: 5000, notes: null, created_at: iso(-20), updated_at: iso(-20) },
    { id: "bk-3", artist_id: ARTIST_ID, client_id: "client-4", request_id: null, service_id: null, status: "confirmed", title: "Session 1", total_price_cents: 50000, deposit_cents: 15000, notes: null, created_at: iso(-45), updated_at: iso(-45) },
    { id: "bk-4", artist_id: ARTIST_ID, client_id: "client-5", request_id: null, service_id: null, status: "completed", title: "Session 1", total_price_cents: 35000, deposit_cents: 10000, notes: null, created_at: iso(-70), updated_at: iso(-70) },
    { id: "bk-5", artist_id: ARTIST_ID, client_id: "client-6", request_id: null, service_id: null, status: "confirmed", title: "Session 1", total_price_cents: 28000, deposit_cents: 8000, notes: null, created_at: iso(-10), updated_at: iso(-10) },
    { id: "bk-6", artist_id: ARTIST_ID, client_id: "client-7", request_id: null, service_id: null, status: "completed", title: "Session 1", total_price_cents: 22000, deposit_cents: 6000, notes: null, created_at: iso(-80), updated_at: iso(-80) },
  ],
  sessions: [
    { id: "sess-1", artist_id: ARTIST_ID, booking_id: "bk-1", client_id: "client-3", location_id: null, session_number: 1, status: "confirmed", scheduled_start: iso(3), scheduled_end: iso(3), duration_minutes: 180, deposit_cents: 10000, deposit_paid: true, balance_cents: 30000, balance_paid: false, notes: null, created_at: iso(-60), updated_at: iso(-60) },
    { id: "sess-2", artist_id: ARTIST_ID, booking_id: "bk-3", client_id: "client-4", location_id: null, session_number: 1, status: "scheduled", scheduled_start: iso(10), scheduled_end: iso(10), duration_minutes: 240, deposit_cents: 15000, deposit_paid: true, balance_cents: 35000, balance_paid: false, notes: null, created_at: iso(-45), updated_at: iso(-45) },
    { id: "sess-3", artist_id: ARTIST_ID, booking_id: "bk-5", client_id: "client-6", location_id: null, session_number: 1, status: "confirmed", scheduled_start: iso(0), scheduled_end: iso(0), duration_minutes: 120, deposit_cents: 8000, deposit_paid: true, balance_cents: 20000, balance_paid: false, notes: null, created_at: iso(-10), updated_at: iso(-10) },
    { id: "sess-4", artist_id: ARTIST_ID, booking_id: "bk-2", client_id: "client-3", location_id: null, session_number: 1, status: "completed", scheduled_start: iso(-15), scheduled_end: iso(-15), duration_minutes: 60, deposit_cents: 5000, deposit_paid: true, balance_cents: 10000, balance_paid: true, notes: null, created_at: iso(-20), updated_at: iso(-20) },
    { id: "sess-5", artist_id: ARTIST_ID, booking_id: "bk-4", client_id: "client-5", location_id: null, session_number: 1, status: "completed", scheduled_start: iso(-65), scheduled_end: iso(-65), duration_minutes: 300, deposit_cents: 10000, deposit_paid: true, balance_cents: 25000, balance_paid: true, notes: null, created_at: iso(-70), updated_at: iso(-70) },
  ],
  payments: [
    { id: "pay-1", artist_id: ARTIST_ID, client_id: "client-3", booking_id: "bk-1", session_id: "sess-1", kind: "deposit", status: "succeeded", amount_cents: 10000, inkd_fee_cents: 1000, currency: "usd", description: null, metadata: {}, stripe_charge_id: null, stripe_payment_intent_id: null, stripe_refund_id: null, stripe_transfer_id: null, processed_at: iso(-59), created_at: iso(-59), updated_at: iso(-59) },
    { id: "pay-2", artist_id: ARTIST_ID, client_id: "client-4", booking_id: "bk-3", session_id: "sess-2", kind: "deposit", status: "succeeded", amount_cents: 15000, inkd_fee_cents: 1500, currency: "usd", description: null, metadata: {}, stripe_charge_id: null, stripe_payment_intent_id: null, stripe_refund_id: null, stripe_transfer_id: null, processed_at: iso(-44), created_at: iso(-44), updated_at: iso(-44) },
    { id: "pay-3", artist_id: ARTIST_ID, client_id: "client-6", booking_id: "bk-5", session_id: "sess-3", kind: "deposit", status: "succeeded", amount_cents: 8000, inkd_fee_cents: 800, currency: "usd", description: null, metadata: {}, stripe_charge_id: null, stripe_payment_intent_id: null, stripe_refund_id: null, stripe_transfer_id: null, processed_at: iso(-9), created_at: iso(-9), updated_at: iso(-9) },
    // A deposit tied to a completed session — NOT counted as "held".
    { id: "pay-4", artist_id: ARTIST_ID, client_id: "client-3", booking_id: "bk-2", session_id: "sess-4", kind: "deposit", status: "succeeded", amount_cents: 5000, inkd_fee_cents: 500, currency: "usd", description: null, metadata: {}, stripe_charge_id: null, stripe_payment_intent_id: null, stripe_refund_id: null, stripe_transfer_id: null, processed_at: iso(-19), created_at: iso(-19), updated_at: iso(-19) },
  ],
  agent_settings: [
    {
      id: "agent-settings-1",
      artist_id: ARTIST_ID,
      autonomy: "draft_only",
      action_class_overrides: {},
      front_desk_enabled: true,
      booking_manager_enabled: true,
      studio_manager_enabled: false,
      growth_advisor_enabled: false,
      client_disclosure_enabled: false,
      escalation_keywords: [],
      quote_min_cents: null,
      quote_max_cents: null,
      created_at: iso(-90),
      updated_at: iso(-1),
    },
  ],
  agent_actions: [],
};
